/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alasku.socialmediadbms;

import static alasku.socialmediadbms.profile.namelbl;
import javax.swing.*;
import java.util.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.*;
import javax.swing.table.*;
/**
 *
 * @author Kurian
 */
//class FlowFeed extends JPanel{
//    private Color[] COLORS = new Color[] {Color.BLUE, Color.CYAN, Color.DARK_GRAY, Color.GRAY, Color.GREEN,
//              Color.LIGHT_GRAY, Color.MAGENTA, Color.ORANGE, Color.PINK, Color.RED,
//              Color.YELLOW, Color.WHITE};
//
//    public FlowFeed() {
//        this.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
//        //
//        Random rand = new Random();
//        for (int i = 0; i < 28; i++) {
//            JPanel aPanel = new JPanel();
//            aPanel.setPreferredSize(new Dimension(50, 50));
//            aPanel.setBackground(COLORS[rand.nextInt(COLORS.length)]);
//            this.add(aPanel);
//        }
//    }
//}

//class GridFeed extends JPanel{
//    private Color[] COLORS = new Color[] {Color.BLUE, Color.CYAN, Color.DARK_GRAY, Color.GRAY, Color.GREEN,
//                                  Color.LIGHT_GRAY, Color.MAGENTA, Color.ORANGE, Color.PINK, Color.RED,
//                                  Color.YELLOW, Color.WHITE};
//    public GridFeed() {
//        this.setLayout(new GridLayout(10,3,3,3));
//        //
//        Random rand = new Random();
//        for (int i = 0; i < 28; i++) {
//            JPanel aPanel = new JPanel();
//            aPanel.setPreferredSize(new Dimension(50, 50));
//            aPanel.setBackground(COLORS[rand.nextInt(COLORS.length)]);
//            JLabel postlbl = new JLabel();
//            try{
//                Class.forName("com.mysql.cj.jdbc.Driver");
//                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mybook","root","");
//                
//                Statement stm = con.createStatement();
//                String content = null;
//                String sql = "select content from posts order by date desc";
//                ResultSet rs = stm.executeQuery(sql);
//                if(rs.next())
//                {
//                    content = rs.getString(i);
//                }
//                postlbl.setText(content);
//                aPanel.add(postlbl);
//                add(aPanel);
//            }
//            catch(Exception e)
//            {
//                e.printStackTrace();
//            }
//            }
////            this.add(aPanel);
//        }
//    }

//class feed extends JScrollPane{
//    for 
//}
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public static String username;
    public home() {
        initComponents();
        //postbox.add(new GridFeed());
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mybook","root","");

            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("select username,content,date from posts order by date desc");
            //int i=0;
            //String[] data = {};
//            while(rs.next()){
//                //data[i] = rs.getString(i);
//                //System.out.println(data[i]);
//                //i++;
//            }
//            data[i] = "/0";
            
            //JList<String> list = new JList<>(data);
            //postbox = new JScrollPane(list);
            while(rs.next())
            {
                String uname = rs.getString("username");
                String content = rs.getString("content");
                Date d = rs.getDate("date");
                Format forma = new SimpleDateFormat("yyyy-MM-dd");
                String date = forma.format(d);

                String tdData[] = {uname,content,date};
                DefaultTableModel tb1Model = (DefaultTableModel)posttab.getModel();
                tb1Model.addRow(tdData);
            }
//            add(postbox);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        //add(postbox);
        namelbl.setText(username);
        //namelbl.setText(username);
    }
    
    
//    FlowFeed flow = new FlowFeed();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchbtn = new javax.swing.JButton();
        postbtn = new javax.swing.JButton();
        probtn = new javax.swing.JButton();
        namelbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        posttab = new javax.swing.JTable();
        logoutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchbtn.setBackground(new java.awt.Color(46, 196, 182));
        searchbtn.setFont(new java.awt.Font("Base Neue SemBd", 0, 12)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        postbtn.setBackground(new java.awt.Color(46, 196, 182));
        postbtn.setFont(new java.awt.Font("Base Neue SemBd", 0, 12)); // NOI18N
        postbtn.setForeground(new java.awt.Color(255, 255, 255));
        postbtn.setText("POST");
        postbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postbtnActionPerformed(evt);
            }
        });

        probtn.setBackground(new java.awt.Color(46, 196, 182));
        probtn.setFont(new java.awt.Font("Base Neue SemBd", 0, 12)); // NOI18N
        probtn.setForeground(new java.awt.Color(255, 255, 255));
        probtn.setText("PROFILE");
        probtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probtnActionPerformed(evt);
            }
        });

        namelbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        namelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        posttab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Posts", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        posttab.setMaximumSize(new java.awt.Dimension(600, 0));
        posttab.setMinimumSize(new java.awt.Dimension(600, 0));
        posttab.setRowHeight(35);
        jScrollPane1.setViewportView(posttab);
        if (posttab.getColumnModel().getColumnCount() > 0) {
            posttab.getColumnModel().getColumn(0).setMinWidth(100);
            posttab.getColumnModel().getColumn(0).setMaxWidth(100);
            posttab.getColumnModel().getColumn(1).setMinWidth(400);
            posttab.getColumnModel().getColumn(1).setMaxWidth(400);
            posttab.getColumnModel().getColumn(2).setMinWidth(100);
            posttab.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        logoutbtn.setBackground(new java.awt.Color(46, 196, 182));
        logoutbtn.setFont(new java.awt.Font("Base Neue SemBd", 0, 12)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(probtn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbtn)
                    .addComponent(postbtn)
                    .addComponent(probtn)
                    .addComponent(logoutbtn)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void probtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probtnActionPerformed
        // TODO add your handling code here:
        dispose();
        profile pro = new  profile();
        profile.namelbl.setText(namelbl.getText());
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mybook","root","");
        
        pro.username = namelbl.getText();
        System.out.println(pro.username+"123");
        String fname;
        String lname;
        
        Statement stm = con.createStatement();
        String sql = "select fname,lname from user where uname ='"+pro.username+"'";
        //String sql2 = "select lname from user where uname ='"+pro.username+"'";
        ResultSet rs = stm.executeQuery(sql);
        if(rs.next()){
        //ResultSet rs = stm.executeQuery(sql2);
        fname = rs.getString(1);
        //System.out.println(r1.getString(1));
        lname = rs.getString(2);
        System.out.println(fname+"543");
        profile.fnamelbl.setText(fname);
        profile.lnamelbl.setText(lname);
        }
        }
        catch(Exception x){
           x.printStackTrace();
        }
        //pro.username = jLabel1.getText();
        pro.show();
    }//GEN-LAST:event_probtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        search s = new search();
        search.username = namelbl.getText();
        s.show();
    }//GEN-LAST:event_searchbtnActionPerformed

    private void postbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        post post = new post();
        post.show();
        post.username = namelbl.getText();
        
    }//GEN-LAST:event_postbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        login log = new login();
        log.show();
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbtn;
    public static javax.swing.JLabel namelbl;
    private javax.swing.JButton postbtn;
    private javax.swing.JTable posttab;
    private javax.swing.JButton probtn;
    private javax.swing.JButton searchbtn;
    // End of variables declaration//GEN-END:variables
}
